### ISSUE TITLE
Can publish a dapp with 0 STT

### ISSUE THREAD

**Issue by asemiankevich** [dap-ps/discover#11]
Android 8

can publish a dapp with 0 STT

Steps:
1. open dev.dap.ps
2. tap submit a dapp
3. fill in the form and submit
4. do not enter any value into SNT field and tap Publish

![image](https://user-images.githubusercontent.com/28752642/62768263-2a138700-ba9f-11e9-83e6-0da0406987b1.png)

**Comment by andytudhope** [comment]
This is expected behaviour.
