### ISSUE TITLE
1 SNT is calculated as 1/18 of SNT for Upvote and Downvote

### ISSUE THREAD

**Issue by churik** [dap-ps/discover#11]
**Steps:**
- create account
- open http://dev.dap.ps 
- tap to upvote any dapp
- enter amount
- tap upvote

**Expected result:** transaction with 1 SNT will be created
**Actual result:**
![photo_2019-07-01 15 19 46](https://user-images.githubusercontent.com/4557972/60439768-ad75c900-9c13-11e9-9b15-0cbed4b9a11e.jpeg)

**Comment by andytudhope** [comment]
Look how useful that new UI is!! Took me 2 days to suspect this. Nice find and will get this fixed ASAP.

**Comment by andytudhope** [comment]
Fixed in https://github.com/dap-ps/discover/commit/c72a17f826df095dbb09fcdfa183aec263097e40
