### ISSUE TITLE
Can't submit new dapp on IOS

### ISSUE THREAD

**Issue by churik** [dap-ps/discover#12]
### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug
*Summary*: can't submit new Dapp on IOS on both latest nightly and release with different errors.

#### Expected behavior
can  submit new dapp

#### Actual behavior
For nightly:
![IMG_2D3D3C3C5649-1](https://user-images.githubusercontent.com/4557972/62768658-9c806900-ba97-11e9-96af-26904f8caf37.jpeg)
For Release:
![IMG_45F9248AD2E3-1](https://user-images.githubusercontent.com/4557972/62768890-26c8cd00-ba98-11e9-8362-ab8be466368f.jpeg)

### Reproduction

[comment]: # (Describe how we can replicate the bug step by step.)
- restored account with STT
- switched to Ropsten
- opened dev.dap.ps
- tapped on “Submit Dapp”
- filled all required details
- on step with SNT settings getting a warning that I’m on Ropsten, not on Mainnet
- filled 2 SNT > Publish

### Additional Information

[comment]: # (Please do your best to fill this out.)
- Status version: nightly 09/08/2018; release 0.13.0
- Operating System: iOS

#### Logs

Log for nightly: [geth.log](https://github.com/dap-ps/discover/files/3485639/geth.log)

**Comment by andytudhope** [comment]
I don't have an IOS device or an easy way of emulating one... Will try and reproduce this with the nightly tomorrow and see where we get to from there.

**Comment by flexsurfer** [comment]
the same if you try to upvote on Android, dapp doesn't ask permissions

**Comment by andytudhope** [comment]
It literally just worked on Android for me, in prod. What Status version?

**Comment by flexsurfer** [comment]
sorry for confusion i'm trying `prod.dap.ps` with real SNT on 0.13 Status release

**Comment by SpasiboKojima** [comment]
Same for me here, still.
Also, if I submitted a DApp from browser, like, 4 weeks ago, do you still accept them? I haven't seen any new DApps since.

**Comment by andytudhope** [comment]
Hmmm, this is super weird, and I cannot reproduce it. @KojimaGeniy - I have not seen any DApps being submitted in the last 9 days - which one were you trying to get in here? Apologies for the delayed response - I have been out of internet connectivity for the last week.

**Comment by rachelhamlin** [comment]
Hmm, okay, I just tested on iOS and had the `Could not establish connection to a node` error.

**Comment by rachelhamlin** [comment]
Oops - we're low on DAI in the bounty account, but I will bounty.

**Comment by andytudhope** [comment]
I can also bounty this... It's strange that iOS is giving us so many errors :disappointed: Can you please specify the version of iOS and of Status that you are running?

**Comment by rachelhamlin** [comment]
Not cute, iOS. Not cute. I'm on a nightly - v1 build, I think from 2 days ago. 

And iphone xs max iOS 13.1.3 :)

**Comment by SpasiboKojima** [comment]
So, should it work now? I still can't see any DApps here.
Also @andytudhope, could you please check again? I submitted the "Totle Swap", the popup said it was approved and it appeared on the page, but it was cached and can only be seen among the "Highest Ranked" DApps, and not in it's category nor in any other browser. Or does it secretly mean that you are still looking into it behind the scene? 🙃

**Comment by andytudhope** [comment]
Hey @KojimaGeniy - so we are definitely having weird iOS issues atm and are in the process of sorting them out. I have looked into Totle and approved it - my sincerest apologies for the delay and trouble you had here. We will be sure to have it fixed in the next few days.

**Comment by andytudhope** [comment]
@jakubgs did your fixes to #16 also take care of this (I think so, but can't really test without iOS devices handy)? @churik any chance you'd be willing to retest quickly if Jakub gives the go ahead so we can try close here?

**Comment by jakubgs** [comment]
I'm not sure since #16 was about a browser with no web3 provider, so no MetaMask or any other built-in wallet. This might still be an issue, we'd have to test.

**Comment by andytudhope** [comment]
Ok cool. @churik will you retest this on dev.dap.ps whenever you have some free time (no rush with all your other work atm!) and we can see if it is still a problem.

**Comment by rachelhamlin** [comment]
FWIW on mainnet yesterday I was able to submit a DApp without any SNT staked—previously having encountered the same error as Chu.

**Comment by rachelhamlin** [comment]
If I test again with SNT staked, can you remove my DApp afterward @andytudhope?

**Comment by andytudhope** [comment]
@rachelhamlin if you test on https://dev.dap.ps with STT, that is equivalent to using dap.ps with SNT.

You need to use the test site so that we don't pollute the production contract with test data, which cannot be deleted (as that is immutable, blah blah blah etc blockchain etc etc :wink: )

**Comment by rachelhamlin** [comment]
Fair enough! Removed from the UI then.

Thank god I have ample STT. :) I just tested on dev.dap.ps and all seems to work. The only minor issue is that once you've submitted, there is no confirmation screen. In fact I can `Stake and publish` again if I'd like. Which is fine, but may confuse folks into double submission if they're not paying attention. Functionally speaking, all seems good now.

**Comment by andytudhope** [comment]
Yeah, that is a separate issue I think. We do confirm it in the little bubble at the top of the screen and - if staked - your DApp appears immediately, but I agree we could make it even clearer. Will create a new issue for that and close here. Maciej is gonna love me with all this design work again :wink:
