### ISSUE TITLE
Can't edit metadata

### ISSUE THREAD

**Issue by andytudhope** [dap-ps/discover#13]
This has been replicated in both Status and Brave. When trying to edit metadata, get an error alerted to the user: "A DApp was not uploaded in the client".

1. Open Status
2. Go to dev.dap.ps
3. Select a DApp you "own" in the sense of being the one who initially ranked it.
4. Scroll to bottom of profile page and select "Edit Metadata"
5. Edit whatever you like and submit it.
6. See the error above appear.

**Comment by iamonuwa** [comment]
I can't find "Edit Metadata" option on both my Status and Brave browsers.

**Comment by andytudhope** [comment]
@iamonuwa it has to be on a DApp that you have submitted. If you still can't find it (bottom of the DApp's profile screen) submit a new one, and I will approve it, after which you should see those 2 buttons appear.

**Comment by iamonuwa** [comment]
> @iamonuwa it has to be on a DApp that you have submitted. If you still can't find it (bottom of the DApp's profile screen) submit a new one, and I will approve it, after which you should see those 2 buttons appear.

I have 2 dapps I submitted. The *Cats*.

**Comment by andytudhope** [comment]
Well, if you can't see the buttons, just submit a new one and I will approve (there was some small issues with approvals earlier, so that might have affected _Cats_, for instance).

**Comment by iamonuwa** [comment]
> Well, if you can't see the buttons, just submit a new one and I will approve (there was some small issues with approvals earlier, so that might have affected _Cats_, for instance).

I'll create one in 1 hour as the Rate Limiter has blocked me till 1 hour

**Comment by andytudhope** [comment]
I'm also being blocked, may be something else because @Perseverance deployed a new version with a fixed contract to handle #11 yesterday - let's wait and see and, yeah, try again in an hour.

We should probably think of upping that rate limiter too, seems pretty restrictive atm.

**Comment by iamonuwa** [comment]
> We should probably think of upping that rate limiter too, seems pretty restrictive atm.

Dev environment should have a friendly rate limiter. Production should be more strict

**Comment by andytudhope** [comment]
This has been fixed in the latest version - see Brave Test, "now edited".
