### ISSUE TITLE
For apps < 100 SNT downvoting costs 0 SNT, so it is not working

### ISSUE THREAD

**Issue by churik** [dap-ps/discover#14]
### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug
*Summary*: as far as I understand value for downvoting is calculated automatically and if app published with SNT value < 100, value for downvoting is 0 SNT, it doesn't affect to app rank

#### Expected behavior
value for downvote is not 0

#### Actual behavior
![photo_2019-08-09 12 34 33](https://user-images.githubusercontent.com/4557972/62773303-20d7e980-baa2-11e9-90ae-ede5554f6310.jpeg)

### Reproduction

- Open dev.dap.ps
- Tap "Downvote" on any dapp < 100 SNT

### Additional Information

[comment]: # (Please do your best to fill this out.)
- Status version: nightly 09/08/2019
- Operating System: Android, iOS

**Comment by andytudhope** [comment]
This is expected behaviour. You have to downvote always by 1% of the current rank, so it is not possible to downvote DApps with less than 100 SNT staked. This makes sense conceptually too, as we don't want people trolling those with very little SNT.
