### ISSUE TITLE
Miscellaneous UI fixes

### ISSUE THREAD

**Issue by errorists** [dap-ps/discover#14]
### Featured cards

- cards should have a mobile breakpoint, so on phones each card takes up the exact % of available space like so
calc 100% width (screen width) - 16 - 24 (margins). let's say the phone is an iPhone, then the result would be 375 - 16 - 24 = 335 for each card.

### Category cards

- Content should be left aligned, like in the [design](https://www.figma.com/file/MYWmd1buvc2AMvUmFP9w42t5/Browser?node-id=932%3A1707). Currently it's centred

### Lists

- On desktop each column in lists should take up the available space proportionally, so let's say there are 3 columns in Highest Rated, each column should then be 33% in width.

### Profiles

- The circles that show how each Dapp ranks on the lists, should take the color of the respective category if available. Currently they're hardcoded blue

- The vertical margin of 'Open chat…' button should be the same on top and bottom. currently it's larger on top. [Design](https://www.figma.com/file/MYWmd1buvc2AMvUmFP9w42t5/Browser?node-id=2128%3A10842) 

- The margin between category text label and 'Open' button is too large, it should be 16px.

### Dapp submission

- The titles in the headers are using the wrong text styles, it should be a `font size 13, font weight 500, transform: uppercase, letter-spacing 0.2`

- The topmost container with the header and close button, it should be fixed in position so that it always appears at the bottom above the content, and does not scroll with the content.

- The bottommost container with the button inside, it should be fixed in position so that it always appears at the bottom above the content, and does not scroll with the content.

- When submitting dapp data, the name text field and URL both are missing correct placeholder styles, they should be grey like the description text field.

### Upvote / Downvote

- Please remove the color coded green-red styles from the buttons. it's Blue when active, grey when inactive.

thanks 🙏

**Comment by andytudhope** [comment]
@iamonuwa there is 150 DAI bounty on this, still getting the same rpc error to do with gas when trying to pay the 10% bounty fee to Gitcoin, so can't issue bounties properly :disappointed:

**Comment by iamonuwa** [comment]
> @iamonuwa there is 150 DAI bounty on this, still getting the same rpc error to do with gas when trying to pay the 10% bounty fee to Gitcoin, so can't issue bounties properly

Reach out to the team for them to resolve this

**Comment by andytudhope** [comment]
have already done so

**Comment by iamonuwa** [comment]
They'll go through it and fix it then

**Comment by iamonuwa** [comment]
> calc 100% width (screen width) - 16 - 24 (margins). let's say the phone is an iPhone, then the result would be 375 - 16 - 24 = 335 for each card.

@errorists app is already using grid to calculate width

**Comment by errorists** [comment]
@iamonuwa can we have a breakpoint for mobile devices (so <480px) to lay out the grid in a pattern where each cell is +/- the desired width. On mobile they get super small where the intention was to have a single cell taking up all the available space and only leaving 16px for other cards. Even an approximation where each card is 90% screen width would be better. Also the margin between cells should be a constant 8px, similar to how it's for categories.

**Comment by iamonuwa** [comment]
Cool

**Comment by iamonuwa** [comment]
> - The topmost container with the header and close button, it should be fixed in position so that it always appears at the bottom above the content, and does not scroll with the content.

> - The bottommost container with the button inside, it should be fixed in position so that it always appears at the bottom above the content, and does not scroll with the content.

Am currently rewriting the modal to accomodate this UI fixes. There should be a header, content and body for the modal. I'll send in the PR for this morning.

**Comment by andytudhope** [comment]
@iamonuwa can you confirm that you have addressed all the above? I have one more note here:

Through all the fixes, we have messed up the columns for each section, and they're behaving very differently, which should not happen.

**On mobile:**
Each section should contain 3 DApps in each column. They should load 1 below the other and, after more than 3 appear in that section, it should scroll horizontally. (This is currently how Highest Ranked works, but Recently Added starts scrolling horizontally immediately).

**On desktop:**
Each section should have 3 columns across, evenly spaced (as in the designs and Maciej's comment above). I think the DApps should load horizontally, and that we shouldn't have more than 5 DApps per column, however I need @errorists input here on how he imagines it working for larger numbers of DApps...

**Comment by iamonuwa** [comment]
I'll take a look now

**Comment by andytudhope** [comment]
@iamonuwa what is the status here and - like on the other issue - can you tell me how much time you have spent on the above so I can create an appropriate bounty?

**Comment by iamonuwa** [comment]
Spent 8 productive hours and 2 unproductive hours. I was sick last weekend. But will be cleared today to resume work. I'll finish this and let you know the total hours spent

**Comment by iamonuwa** [comment]
> @iamonuwa can you confirm that you have addressed all the above? I have one more note here:
> 
> Through all the fixes, we have messed up the columns for each section, and they're behaving very differently, which should not happen.

@andytudhope @errorists PTAL https://www.dropbox.com/s/nfvbejqhby0k1r1/Status%20Grid.mp4?dl=0

**Comment by andytudhope** [comment]
OK, this looks mostly good to me. For some reason, the Social Networks card is center-aligned on the mobile view in that vid though?

Otherwise, I think we're good to go here.

**Comment by iamonuwa** [comment]
> OK, this looks mostly good to me. For some reason, the Social Networks card is center-aligned on the mobile view in that vid though?
Oh! Didn't see this. I've fixed it now.


> Also, what about the modal rewrite you mentioned earlier in this thread?
Like I said, I could either rewrite it or use an existing react modal component as a wrapper to get it done. It will be ready today

**Comment by andytudhope** [comment]
Fixed in #8
