### ISSUE TITLE
Status crashes at attempt to set video for icon when submitting dapp

### ISSUE THREAD

**Issue by churik** [dap-ps/discover#17]
### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug
*Summary*: crash at attempt to set video as icon on "Submit DApp" page

#### Expected behavior
No option for video.
Actually on IOS 13.0 (still in beta) there is no option, but on latest IOS (12.4) it is still the case.

### Reproduction

[comment]: # (Describe how we can replicate the bug step by step.)
- restore account with STT
- switch to Ropsten
- open dev.dap.ps
- tap on “Submit Dapp”
- tap on "Choose icon"
- select "Take photo or video"
![photo_2019-08-09 13 56 41](https://user-images.githubusercontent.com/4557972/62778028-7ebefe00-baaf-11e9-875b-84350b445f61.jpeg)
- tap on "Video"

### Additional Information

[comment]: # (Please do your best to fill this out.)
- Status version: nightly 09/08/2018; release 0.13.0
- Operating System: iOS (11.4.1, 12.4)

**Comment by asemiankevich** [comment]
**NOTE:** i can't see [Video] option on iOS 13 beta4 , seems iOS versioning dependant
![image](https://user-images.githubusercontent.com/28752642/62786364-1847d900-bacb-11e9-9beb-d4c99ddb2ac4.png)

**Comment by andytudhope** [comment]
This is dope edge case to find :heart: But I think I will close here as this is more a Status issue than our issue and we just need to make sure only the photo option is accessible. What is weird is that different iOS versions have different options...
