### ISSUE TITLE
Implementation Review Fixes

### ISSUE THREAD

**Issue by andytudhope** [dap-ps/discover#2]
There are a good number of small stylistic fixes to be done based on the Implementation Review, as it appears that the team responsible for building v2 did not export the styles exactly as they are described in Figma.

Currently, there are 24 minor issues to be fixed, all of which can be found under the "Implementation Review" page in [this link](https://www.figma.com/file/MYWmd1buvc2AMvUmFP9w42t5/Discovery?node-id=2903%3A17528)

@iamonuwa - would you like to have a go at this? We can set up a call to make sure we are on exactly the same page about how to export stuff and use it correctly from Figma and then implementing the fixes should be relatively straightforward work.

**Comment by iamonuwa** [comment]
Of course. Hit me up on Twitter let's fix it. 😁

**Comment by andytudhope** [comment]
2 other issues while we're at it. 

1. When you submit a DApp, the pop-up box at the top still contains filler text for the description, rather than the text you enter.

2. In the "Highest Ranked" section, only the description should show, NOT the url - as shown in the designs. Clicking on the image or description should still take you to that DApp's description page on dap.ps

**Comment by andytudhope** [comment]
Fixed by https://github.com/dap-ps/discover/commit/a4e5c82ecef789daa5fe18c62cf984a6f921f343
