### ISSUE TITLE
Endless "Waiting confirmation of the network" at attempt to upvote app with empty balance or if you cancel transaction

### ISSUE THREAD

**Issue by churik** [dap-ps/discover#4]
**Steps:**
- create account
- open http://dev.dap.ps with empty balance
- try to Upvote Dapp

**Expected result:** no popup is shown
**Actual result:** 
<img width="230" alt="dsfsdf" src="https://user-images.githubusercontent.com/4557972/60431136-4fd78180-9bff-11e9-8a62-f38e87740b44.png">

**Comment by andytudhope** [comment]
FIxed in https://github.com/dap-ps/discover/pull/15
