### ISSUE TITLE
Link for dai is outdated

### ISSUE THREAD

**Issue by bgits** [dap-ps/discover#5]
Link should be cdp.makerdao.com

![Screenshot_20190808-130518](https://user-images.githubusercontent.com/4020296/62700812-d62a7480-b9b0-11e9-9318-6af924fe98fc.jpg)

**Comment by andytudhope** [comment]
Hey @bgits :wave: Can you load cdp.makerdao.com in Status? I grant it permission, but am stuck forever with loading... on the main screen? Either way though, thanks for this note, I will update this link for launch

**Comment by bgits** [comment]
I did get it to load in Status. iOS.

**Comment by andytudhope** [comment]
Just updated.
