### ISSUE TITLE
When editing SNT value for "Upvote" nothing happens if submit it via keyboard

### ISSUE THREAD

**Issue by churik** [dap-ps/discover#5]
**Steps:**
- create account
- open http://dev.dap.ps 
- tap to upvote any dapp
- edit value 
-  tap on "Enter" (Go) on native keyboard

**Expected result:** keyboard is closed or sign transaction screen is opened
**Actual result:**  nothing happens, keyboard overlaps "Upvote" button, so it is not obvious that it should be clicked
![photo_2019-07-01 13 04 16](https://user-images.githubusercontent.com/4557972/60431734-c2952c80-9c00-11e9-98d9-b4779ce52765.jpeg)

**Comment by andytudhope** [comment]
Fixed in https://github.com/dap-ps/discover/pull/15
