### ISSUE TITLE
Can't navigate to searched Dapps

### ISSUE THREAD

**Issue by churik** [dap-ps/discover#50]
Steps:
1) open https://dap.ps 
2) in search field type any DApp (i.e. "Airswap")
3) Tap on Search result

Expected, that will be navigated to Airswap dapp
In fact, nothing happens

Build: nightly 21/10/2019
Device: LG V20 (Android 8)
![screencast 2019-10-21 16-43-14](https://user-images.githubusercontent.com/4557972/67215631-1df26100-f422-11e9-824c-6212bd394dc5.gif)

**Comment by andytudhope** [comment]
There is something weird happening that is preventing the default action from occurring (as I can open the link in a new tab by right clicking when on desktop). My suspicion is that this weirdness likely comes from [this file](https://github.com/dap-ps/discover/blob/master/src/common/components/Search/Search.jsx).

Sadly, @iamonuwa has done another disappearing act on me, but perhaps he'll be able to point to the issue when he gets back?

**Comment by iamonuwa** [comment]
🙈

**Comment by iamonuwa** [comment]
Expect both issues today

**Comment by andytudhope** [comment]
cool sgtm :heart:

**Comment by iamonuwa** [comment]
Figured out the problem. Working on resolving it now
