### ISSUE TITLE
AWS CloudFront URS in newly submitted Dapps in MongoDB

### ISSUE THREAD

**Issue by jakubgs** [dap-ps/discover#55]
@andytudhope found an issue where URLs of images for newly submitted Dapps are ones from CloudFront CDN rather than the proper ones using `https://dap.ps/` url, like so:
```
http://awseb-e-s-awsebloa-202jh07bu8jc-809432613.us-east-1.elb.amazonaws.com/metadata/image/QmRMos8NA8e1Nydkv1qZKECnFM6SrPCR4hR2X7EvNw2kQR
```
Here's an example in the DB:
![unnamed](https://user-images.githubusercontent.com/2212681/70631891-256a0580-1c2e-11ea-85a5-11079eb7df54.png)

**Comment by jakubgs** [comment]
As far as I can tell the `image` attribute is set here:
https://github.com/dap-ps/discover/blob/bf8b9bcbad0a4dec550a9d98a27fb62f7b8a38ce/src/modules/Submit/Submit.jsx#L201-L209
And it seems to come from the `props`.
https://github.com/dap-ps/discover/blob/bf8b9bcbad0a4dec550a9d98a27fb62f7b8a38ce/src/modules/Submit/Submit.jsx#L338-L341
Does this mean that when I select an image it is immediately uploaded to IPFS? And if so, how is it returned to the app.

**Comment by jakubgs** [comment]
And indeed, I created a new Dapp on https://dev.dap.ps/ named `kotlet.io` and we can see the url:
```
admin@node-01.us-east-1a.db.dev:~ % mongo -u root -p $MONGO_PASS
MongoDB shell version v4.0.13
...
> use dev-dap-ps
switched to db dev-dap-ps

> show collections
dappsimages
dappsmetadatas

> db.dappsmetadatas.find({email: "x@kotlet.io"}).pretty()
{
	"_id" : ObjectId("5df107273c338c6f3cd2241f"),
	"status" : "NEW",
	"details" : {
		"name" : "kotlet.io",
		"url" : "https://kotlet.io",
		"description" : "kotlet.io",
		"category" : "OTHER",
		"image" : "http://awseb-e-z-awsebloa-drsp96a9o657-2001638989.us-east-1.elb.amazonaws.com/metadata/image/QmZhTrvs4yJejcywp1gPenZW2g9LuMk8xXi2XwXTtDULgF",
		"dateAdded" : 1576077093799,
		"uploader" : "0x9b64770c9485a5188d238c305e53627a67c05d7d"
	},
	"compressedMetadata" : "0x51c054dbef40a02f3ba9971f3cc20e874e959e7dd592338d677309160614c6d1",
	"email" : "x@kotlet.io",
	"hash" : "QmcdW3KG6YdvN6DzkfPWpaELV3AYYnpxbudBHMVCxwEPMx",
	"__v" : 0
}
```

**Comment by jakubgs** [comment]
So it looks like the image is posted via JSON inline to the path:
```
POST https://dev.dap.ps/metadata
```
![dap_image_post](https://user-images.githubusercontent.com/2212681/70635155-b8f20500-1c33-11ea-8156-2a09e090e1d4.png)
So the issue must be on the backend side, rather than the frontend UI.

**Comment by jakubgs** [comment]
The code that handles the `/metedata` path is:
https://github.com/dap-ps/discover/blob/bf8b9bcbad0a4dec550a9d98a27fb62f7b8a38ce/back-end/routes/dapps-routes.js#L12
And is defined here:
https://github.com/dap-ps/discover/blob/bf8b9bcbad0a4dec550a9d98a27fb62f7b8a38ce/back-end/controllers/dapps-metadata-controller.js#L22-L43
And even deeper:
https://github.com/dap-ps/discover/blob/bf8b9bcbad0a4dec550a9d98a27fb62f7b8a38ce/back-end/services/dapp-metadata-service.js#L8-L42

**Comment by jakubgs** [comment]
Found it:
https://github.com/dap-ps/discover/blob/bf8b9bcbad0a4dec550a9d98a27fb62f7b8a38ce/back-end/services/dapp-image-service.js#L27
I don't see why we have to set the full url at all, why not just the path?

**Comment by andytudhope** [comment]
No need for the full URL, you seem to be correct. Let's just set the path if that will prevent this from happening. My apologies for not creating this issue sooner, the electricity has just come back on here (have basically been without connection for a week and a half now :disappointed:)

**Comment by jakubgs** [comment]
That's shitty. I'm currently getting drunk. I'll fix it tomorrow.

**Comment by jakubgs** [comment]
The fix seems to work:
```
> db.dappsmetadatas.find({email: "ihave@autism.io"}).pretty()
{
	"_id" : ObjectId("5df20b080d472e0a6ff2a893"),
	"status" : "NEW",
	"details" : {
		"name" : "autism.io",
		"url" : "https://autism.io",
		"description" : "yep",
		"category" : "OTHER",
		"image" : "/metadata/image/QmUNhcMGY2tSYLpaXwzndYhF16enDymsGKY3KHBpxzDS1t",
		"dateAdded" : 1576143623721,
		"uploader" : "0x9b64770c9485a5188d238c305e53627a67c05d7d"
	},
	"compressedMetadata" : "0xc3d95f8a89e55768f3252b6b09bbcc76e2a1310c7a874690ddae7ee4627b7633",
	"email" : "ihave@autism.io",
	"hash" : "QmXxdTo3xg6dEfHtBxPzkgpSg1zUj7DwEdd2Fir4CEonEG",
	"__v" : 0
}
```
And the image is downloaded correctly:
![dapp_image_success](https://user-images.githubusercontent.com/2212681/70703301-16d42a80-1cd0-11ea-9c12-878fbbf4dde0.png)

**Comment by jakubgs** [comment]
Although I found one issue in which I had to manually invalidate the `/metadata/all` path in our CloudFront cache because it wouldn't let me see the newly approved Dapps. I'll have to take a look at that. New issue: https://github.com/dap-ps/infra-dapps/issues/17
