### ISSUE TITLE
Search bar issues reported

### ISSUE THREAD

**Issue by StatusSceptre** [dap-ps/discover#60]
Search yields nothing on iOS, perhaps tied to [lack of DApps populating](https://github.com/dap-ps/discover/issues/16). 

Seems to work fine on Samsung Galaxy S8 and in web browsers.

But—we have a report that in Google Chrome, search works on first runthrough but not subsequent ones (no results, cursor disappearing). I can not reproduce it.

**Comment by iamonuwa** [comment]
@StatusSceptre @andytudhope here to investigate and fix

**Comment by andytudhope** [comment]
@iamonuwa I thought you didn;t have an iOS device? If you can replicate and fix, I will make sure to put a bounty here.

**Comment by iamonuwa** [comment]
> @iamonuwa I thought you didn;t have an iOS device? If you can replicate and fix, I will make sure to put a bounty here.

Just checked it out. On a Safari browser, search works fine. @StatusSceptre which browser are you testing with?

**Comment by andytudhope** [comment]
Unable to replicate, and no further comments coming though, so am closing here in the interests of keeping tight track of issue in this repo.
