### ISSUE TITLE
IPFS hashes are wrong

### ISSUE THREAD

**Issue by andytudhope** [dap-ps/discover#71]
We never got around to actually pinning images for each DApp into IPFS due to issues with Infura and budget constraints.

Now, it is time to fix that. See [this issue](https://github.com/status-im/infra-ipfs/issues/2#issuecomment-574601860) for context around the Infra needs. While Jakub sets up that stuff, we need to figure out why the way we have been getting the hash for each image is different than what is returned from IPFS and fix it, so that work with subgraphs etc can continue more smoothly.

@iamonuwa @nanspro I am happy for either of you to take a look here if you're keen and will put up a bounty if you are. I would start by looking [here](https://github.com/dap-ps/discover/blob/master/back-end/services/ipfs-service.js#L21).

**Comment by iamonuwa** [comment]
Available to work on it

**Comment by andytudhope** [comment]
See if you agree with our findings in the issue linked above that the image hashes are indeed wrong (the actual hashes for the DApp objects seem correct, which is strange) and hit me up with an estimate of time to fix and I will create a bounty here.

**Comment by andytudhope** [comment]
@iamonuwa any progress here? Jakub is mostly done on the infra side... https://github.com/status-im/infra-ipfs/issues/2#issuecomment-575667917

**Comment by iamonuwa** [comment]
Actually waiting for him to complete his end.

**Comment by nanspro** [comment]
@iamonuwa could take a look at https://pinata.cloud/ if you wanna pin to ipfs

**Comment by andytudhope** [comment]
Fixed in https://github.com/dap-ps/discover/commit/9dee93c0773793b8222464b3055530989285aa0c
