### ISSUE TITLE
Nothing shows up on browser

### ISSUE THREAD

**Issue by corpetty** [dap-ps/discover#9]
Wanted to play around on dev.dap.ps and none of the rankings show up.

#### Things Tried
- cleared cache
- multiple browsers (chrome and firefox)

#### Misc
- It is strange behavior, @jakubgs is on the same local network and it works for him.

**Comment by andytudhope** [comment]
There may be issues in firefox with fetching anything from IPFS (there is locally). Honestly not sure how to check or fix this though as I can't reproduce in Firefox or Brave....

**Comment by iamonuwa** [comment]
This is a case with the idb, I'll take a look at the configuration. Most times it does not store cached data from IPFS.

**Comment by andytudhope** [comment]
@corpetty we have deployed a new version. Can you please check this issue again and lmk if I can close it, or if you can still reproduce?
